name: newgrouper39
channels:
  - conda-forge
  - pyg
dependencies:
  - python=3.12
  - boost
  - cmake
  - rdkit
  - librdkit-dev
  - librdkit
  - rdkit-dev
  - rdkit-postgresql
  - eigen
  - pybind11
  - mbuild
  - nauty
  - jupyter
  - jupyter
  - seaborn
  - cairosvg
  - pyg
  - pytest-benchmark
  - pytest
  - pip:
    - grakel
