name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yml

    - name: Install dependencies
      run: |
        conda env update -n ${{ matrix.python-version }} --file environment.yml
        conda activate ${{ matrix.python-version }}

    - name: Run tests with pytest
      run: pytest
