name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        create-args: >- # beware the >- instead of |, we don't split on newlines but on spaces
          python=3.9

    - name: Install dependencies
      run: micromamba install --file environment.yml --yes


    - name: Run tests with pytest
      run: pytest
      shell: micromamba-shell {0}
