name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: test-env
        create-args: python=3.9

    - name: Install dependencies
      run: micromamba install -n test-env librdkit-dev librdkit rdkit-dev rdkit-postgresql boost cmake rdkit eigen pybind11 networkx pytest llvm-openmp -y

    - name : Install nauty
      run: micromamba install -n test-env -c conda-forge nauty -y
  
    - name: List libraries in test-env
      run: ls /home/runner/micromamba/envs/test-env/lib | grep omp

    - name: Install package
      run: micromamba run -n test-env python setup.py build_ext --inplace;micromamba run -n test-env pip install .

    - name: Run tests with pytest
      run: micromamba run -n test-env pytest Grouper/tests
