name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        create-args: >- # beware the >- instead of |, we don't split on newlines but on spaces
          -n test-env
          python=3.9

    - name: Install dependencies
      run: micromamba install librdkit-dev librdkit rdkit-dev rdkit-postgresql boost cmake rdkit eigen pybind11

    - name: Install package
      run: pip install .
      shell: micromamba-shell {0}

    - name: Run tests with pytest
      run: pytest genGrouper/tests
      shell: micromamba-shell {0}
